### ISSUE TITLE
Bug: Division by zero error

### ISSUE THREAD

**Issue by HolyOne** [Dentrax/Z00bfuscator#3]
`
/ _  // _ \ / _ \| |__  / _|_   _ ___  ___ __ _| |_ ___  _ __
\// /| | | | | | | '_ \| |_| | | / __|/ __/ _` | __/ _ \| '__|
 / //\ |_| | |_| | |_) |  _| |_| \__ \ (_| (_| | || (_) | |
/____/\___/ \___/|_.__/|_|  \__,_|___/\___\__,_|\__\___/|_|

--------------------------------------------------------

[0]: Starting...

[1]: Loading assemblies... : [%10]

[ERR]: Module load failed: Format of the executable (.exe) or library (.dll) is invalid.

[2]: Starting obfuscate... : [%20]

Unhandled Exception: System.DivideByZeroException: Attempted to divide by zero.
   at Z00bfuscator.Obfuscator.AsyncStartObfuscation() in D:\Temp\AutoDirectory379\Z00bfuscator\Z00bfuscator\Obfuscator.cs:line 124
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
`

**Comment by init5-SF** [comment]
Having the same error with some binaries.

**Comment by Dentrax** [comment]
Hey, @HolyOne @init5-SF! Thanks for dropping this here. I do not maintain this project anymore, so any PR would be appreciated! I can approve if you find a way out about the fix. 🙏
